### ISSUE TITLE
Custom Map Problems

### ISSUE THREAD

**Issue by Funkadere** [Nukem9/LinkerMod#27]
Hello,
My custom maps (Nova Six and Fury's Temple) seem to have some problems.
When I try to load up Fury's Temple, the screen goes black and then shows this error:
"Cant load image ~$black-r&$white-r&$black-r&~~95193bbe"
![capture](https://cloud.githubusercontent.com/assets/24888589/21601823/19528520-d1da-11e6-8c05-1902757e0166.PNG)

Nova Six can load fine, but the only thing that works is the HUD.

I tried installing again and again, but it didn't work.
The only DLC I have is Annihilation, do I need the other DLC's?

Please help me! Thank you.

**Comment by SE2Dev** [comment]
Fury's Temple currently requires *both* the Annihilation DLC and the First Strike DLC. I've spoken with LilRobot and he's said that he has since fixed the dependency on First Srike and is waiting for the ModMe downloads page renovations to be completed.

As for Nova Six, I'd assume you either set the mod up incorrectly or are using an outdated version of game_mod. Did you follow the guide here: https://github.com/Nukem9/LinkerMod/wiki/Adding-Legacy-Mods

**Comment by Funkadere** [comment]
Oh, I see. Thank you!
